### PR TITLE
Cordova iOS platform 4.0.0 fix

### PR DESCRIPTION
**Pull request by uerceg**
* MAC MD5 reading from iOS platform is now removed.
* `initWithWebView` is now removed from Cordova iOS platform 4.0.0 so we removed it from our SDK and replaced with `pluginInitialize` method.
* Native iOS SDK updated to version 4.5.0.
* Native Android SDK updated to version 4.2.0.

### CODE REVIEW

**Comment by JiDW** [comment]
Will this be merged soon please ? We need this to be able to compile our project inside cocoon.io

**Comment by uerceg** [comment]
Yep, in next few days it will be merged.

**Comment by JiDW** [comment]
Ok thanks :)

**Comment by ikostic** [comment]
I can wait for 4.2.0 :) Preparing project build with cordova-ios 4.0

**Comment by uerceg** [comment]
And it's live.

**Comment by ikostic** [comment]
Working nice, thanks for keeping us up to date. :)

**Pull request merged**
