### PR TITLE
Changed configuration to in app configuration + install from repository

### PR DESCRIPTION
**Pull request by johannesreichard**
- Added in app configuration by calling the plugin to add configuration - removed old config file.
- Added build script for release. Android and IOS sdk need to be aviable directly for installation from git repository ( there is no way to resolve submodules on cordova plugin installation ).
- Added google playservices as dependency - removed need to install manually.
- Removed hook, there is no more need to manually replace the config parameter in adjust.js.

### CODE REVIEW

**Comment by Hirbod** [comment]
@johannesreichard 
Thank you so much for your effort! Dead simple and looks good, I will give it a try in few minutes.

**Comment by Hirbod** [comment]
Just tried it...

```
Failed to install 'com.adjust.sdk':Error: Uh oh!
cannot find "/Users/Hirbod/Desktop/appdev/Nachbarschaft/plugins/com.adjust.sdk/lib/ios/Adjust.m" ios <source-file>
    at module.exports.source-file.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:52:48)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
Error: Uh oh!
cannot find "/Users/Hirbod/Desktop/appdev/Nachbarschaft/plugins/com.adjust.sdk/lib/ios/Adjust.m" ios <source-file>
    at module.exports.source-file.install (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:52:48)
    at Object.ActionStack.process (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)
```

**Comment by Hirbod** [comment]
Ok this seems not to be related to your fork. I can't even install this SDK with the default procedere

**Comment by johannesreichard** [comment]
Atm I have the same problem, I will try to fix this after lunch.

**Comment by Hirbod** [comment]
Seems like they have moved out some code from the repository into ther "release" page.. #18

**Comment by johannesreichard** [comment]
Sry for the inconvenience, but that should fix it.

**Comment by sandstrom** [comment]
friendly ping @wellle

**Comment by wellle** [comment]
Hi @sandstrom :wave:

**Comment by sandstrom** [comment]
@wellle Is this something you'd be willing to take a look at? It would make installation less cumbersome.

**Comment by wellle** [comment]
Of course! But we're currently busy with Android SDK version 4.

**Comment by uerceg** [comment]
@johannesreichard @Hirbod @sandstrom We have recently released `Cordova SDK v4.0.0` where most of these issue should be fixed. Give it a try and let us know if there's anything else you would like us to add.

**Comment by sandstrom** [comment]
@uerceg Great with a new release! Are there any release notes? A simple `CHANGELOG.md` in the root directory would be very helpful.

**Comment by uerceg** [comment]
@sandstrom Thanks for the feedback. We don't have doc like that at the moment, but we'll take it in consideration for future updates. 

At the moment we do offer small migration guide where we try to describe biggest changes in SDK integration for users. You can find it in here: https://github.com/adjust/cordova_sdk/blob/master/doc/migrate.md

And of course, everything what is new and introduced in new version of SDK is still described in main README.md.

**Comment by sandstrom** [comment]
@uerceg that would be great! Here are a few arguments in favour of keeping a changelog: http://keepachangelog.com/

Probably wouldn't take more than half an hour to write one up retroactively. It'll save your users a lot of time and make your software more approachable!

**Pull request closed without merging**
